name: Gittag
on:
  push:
    branches:
      - "main"
jobs:
  Gittag:
    runs-on: ubuntu-latest
    steps:
      - name: Git get tag
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - name: Some other step
        with:
          tagname: ${{ steps.tagName.outputs.tag }}
      - name: Yet another ste–∑
        run: |
         echo $GIT_TAG_NAME
