name: Gittag
on:
  push:
    branches:
      - "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Extract tag name
         id: tag
         uses: actions/github-script@0.2.0
         with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
       - name: Echo
         run: echo ${{ steps.tag.outputs.result }}
